import React from 'react';
import { ScreenType } from '../types';

interface DocumentsViewProps {
  onNavigate: (screen: ScreenType) => void;
  onDownloadItem: (title: string) => void;
}

export const DocumentsView: React.FC<DocumentsViewProps> = ({
  onNavigate,
  onDownloadItem,
}) => {
  const documents = [
    {
      id: 'doc-1',
      title: 'Master_CV_Sarah_Jenkins.pdf',
      type: 'Master Resume',
      updated: '2 days ago',
      size: '240 KB',
      format: 'PDF',
      score: 94,
      targetRole: 'Senior Product Designer',
      icon: 'description',
    },
    {
      id: 'doc-2',
      title: 'AcmeCorp_Tailored_CV_Oct2024.pdf',
      type: 'Tailored Resume',
      updated: '4 hours ago',
      size: '215 KB',
      format: 'PDF',
      score: 85,
      targetRole: 'Senior Product Designer (Acme Corp)',
      icon: 'auto_awesome',
    },
    {
      id: 'doc-3',
      title: 'AcmeCorp_Cover_Letter.docx',
      type: 'Cover Letter',
      updated: '4 hours ago',
      size: '48 KB',
      format: 'DOCX',
      score: 90,
      targetRole: 'Acme Corp Hiring Manager',
      icon: 'mail',
    },
    {
      id: 'doc-4',
      title: 'TechFlow_Tailored_CV.pdf',
      type: 'Tailored Resume',
      updated: '3 days ago',
      size: '220 KB',
      format: 'PDF',
      score: 88,
      targetRole: 'Senior UX Architect',
      icon: 'auto_awesome',
    },
  ];

  return (
    <div id="documents-screen" className="p-4 sm:p-6 md:p-8 max-w-[1240px] mx-auto space-y-6 sm:space-y-8 animate-fade-in">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h1 className="font-headline text-[22px] sm:text-[28px] font-bold text-[#e5e2e1] tracking-tight">
            Document Repository
          </h1>
          <p className="font-body text-[13.5px] sm:text-[15px] text-[#c3c6d7]">
            All master profiles, tailored resumes, and cover letters generated by JobPal AI
          </p>
        </div>

        <button
          onClick={() => onNavigate('profile')}
          className="flex items-center gap-2 px-4 py-2 rounded-xl bg-[#201f1f] hover:bg-[#2a2a2a] border border-[#434655]/60 text-[#c3c6d7] hover:text-white font-headline text-[13px] font-semibold transition-all cursor-pointer shadow-sm"
        >
          <span className="material-symbols-outlined text-[18px]">account_circle</span>
          <span>Edit Master Profile</span>
        </button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 sm:gap-6">
        {documents.map((doc) => (
          <div
            key={doc.id}
            className="bg-[#1c1b1b] border border-[#434655]/40 rounded-2xl p-4 sm:p-6 shadow-lg flex flex-col justify-between space-y-4 hover:border-[#8d90a0]/60 transition-all"
          >
            <div className="flex items-start gap-3.5">
              <div className="w-11 h-11 rounded-xl bg-[#353534] border border-[#434655]/50 flex items-center justify-center text-[#b4c5ff] shrink-0">
                <span className="material-symbols-outlined text-[22px]">{doc.icon}</span>
              </div>
              <div className="overflow-hidden">
                <div className="flex items-center gap-2">
                  <h3 className="font-headline text-[16px] font-bold text-[#e5e2e1] truncate">
                    {doc.title}
                  </h3>
                </div>
                <p className="font-body text-[13px] text-[#b4c5ff] font-medium mt-0.5">
                  {doc.type} • {doc.targetRole}
                </p>
                <div className="flex items-center gap-3 text-[12px] text-[#8d90a0] mt-2">
                  <span>Updated {doc.updated}</span>
                  <span>•</span>
                  <span>{doc.size}</span>
                  <span>•</span>
                  <span className="text-[#4edea3] font-semibold">{doc.score}% Match</span>
                </div>
              </div>
            </div>

            <div className="flex items-center justify-end gap-2 pt-2 border-t border-[#434655]/30">
              {doc.type === 'Cover Letter' ? (
                <button
                  onClick={() => onNavigate('cover-letter')}
                  className="px-3.5 py-1.5 rounded-lg bg-[#353534] hover:bg-[#434655] text-[#b4c5ff] text-[12px] font-semibold transition-colors cursor-pointer"
                >
                  Open Editor
                </button>
              ) : (
                <button
                  onClick={() => onNavigate('tailored-cv')}
                  className="px-3.5 py-1.5 rounded-lg bg-[#353534] hover:bg-[#434655] text-[#b4c5ff] text-[12px] font-semibold transition-colors cursor-pointer"
                >
                  View Resume
                </button>
              )}
              <button
                onClick={() => onDownloadItem(doc.title)}
                className="px-4 py-1.5 rounded-lg bg-[#2563eb] hover:bg-[#1d4ed8] text-white text-[12px] font-semibold transition-colors flex items-center gap-1.5 cursor-pointer"
              >
                <span className="material-symbols-outlined text-[16px]">download</span>
                <span>Download</span>
              </button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};
