import { UserProfile, AtsBreakdown, CoverLetterData, JobApplication, TailoredCvData } from './types';

export const INITIAL_USER: UserProfile = {
  name: 'Sarah Jenkins',
  email: 'sarah.jenkins@example.com',
  phone: '+1 (555) 019-2834',
  state: 'CA',
  country: 'USA',
  location: 'San Francisco, CA',
  primaryGoal: 'actively_searching',
  experienceLevel: 'senior',
  role: 'AI Systems Engineer | Machine Learning & Python Backend Developer',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=300',
  plan: 'Premium Plan',
  hourlyRate: '$65.00/hr',
  hoursPerWeek: 'More than 30 hrs/week',
  availabilityStatus: 'Available for work',
  bio: `I build the Brain (AI) and the Body (Backend) of your product.\n\nMost developers can build a website, and most data scientists can build a model in a notebook. I bridge that gap: I am an AI Systems Engineer who builds production-ready products that are both intelligent and scalable.\n\nWith 5+ years of experience in classical Machine Learning and a deep specialization in Generative AI (LLMs, RAG, agentic workflows, LangChain, FastAPI), I deliver high-throughput, low-latency applications with clean code architecture and enterprise-grade reliability.`,
  experienceCount: 3,
  educationCount: 2,
  projectsCount: 4,
  skills: [
    'Python',
    'FastAPI',
    'Machine Learning',
    'Artificial Intelligence',
    'Large Language Models',
    'TensorFlow',
    'PyTorch',
    'Retrieval Augmented Generation',
    'PostgreSQL',
    'AI Chatbots',
    'LangChain',
    'Docker & Kubernetes',
  ],
  workingStyles: [
    'Solution Oriented',
    'Accountable for Outcomes',
    'Rapid Prototyping',
    'Clear Asynchronous Communication',
  ],
  languages: [
    { id: 'lang-1', language: 'English', proficiency: 'Native or Bilingual' },
    { id: 'lang-2', language: 'French', proficiency: 'Conversational' },
    { id: 'lang-3', language: 'Spanish', proficiency: 'Basic' },
  ],
  linkedAccounts: [
    {
      id: 'acc-1',
      provider: 'GitHub',
      username: 'sarahjenkins-dev',
      url: 'https://github.com/sarahjenkins-dev',
      verified: true,
      sinceYear: '2021',
    },
    {
      id: 'acc-2',
      provider: 'LinkedIn',
      username: 'sarah-jenkins-ai',
      url: 'https://linkedin.com/in/sarah-jenkins-ai',
      verified: true,
      sinceYear: '2020',
    },
    {
      id: 'acc-3',
      provider: 'StackOverflow',
      username: 'sarah-j-tech',
      url: 'https://stackoverflow.com/users/sarah-j',
      verified: true,
      sinceYear: '2022',
    },
  ],
  certifications: [
    {
      id: 'cert-1',
      title: 'AWS Certified Machine Learning – Specialty',
      issuer: 'Amazon Web Services',
      date: 'Issued Nov 2023 · Expires Nov 2026',
      credentialId: 'AWS-MLS-984210',
      credentialUrl: 'https://aws.amazon.com/verification',
    },
    {
      id: 'cert-2',
      title: 'DeepLearning.AI Generative AI with LLMs',
      issuer: 'DeepLearning.AI & Coursera',
      date: 'Issued Aug 2023',
      credentialId: 'DLAI-LLM-55209',
      credentialUrl: 'https://coursera.org/verify',
    },
  ],
  projects: [
    {
      id: 'proj-1',
      title: 'Enterprise RAG Search & Autonomous Document Agent',
      description:
        'Architected a multi-tenant semantic search engine indexing 500k+ enterprise PDFs using Milvus vector DB, FastAPI, and hybrid keyword-dense retrieval, cutting query latency by 45%.',
      role: 'Lead AI Engineer',
      link: 'https://github.com/sarahjenkins-dev/enterprise-rag-agent',
      skills: ['Python', 'FastAPI', 'Milvus', 'LangChain', 'OpenAI'],
      status: 'Published',
    },
    {
      id: 'proj-2',
      title: 'Real-time High Frequency Fraud Detection Pipeline',
      description:
        'Engineered streaming ML inference service with Kafka and PyTorch, scoring 12,000 transactions/sec under 18ms p99 latency with 99.4% precision.',
      role: 'Backend & ML Engineer',
      link: 'https://github.com/sarahjenkins-dev/streaming-fraud-guard',
      skills: ['PyTorch', 'Kafka', 'Docker', 'PostgreSQL', 'Redis'],
      status: 'Published',
    },
    {
      id: 'proj-3',
      title: 'Automated Code Review & Security Analysis Bot',
      description:
        'Built GitHub action integration using LLMs to perform automated static vulnerability audits and cyclomatic complexity linting across 40+ engineering repositories.',
      role: 'Creator & Maintainer',
      link: 'https://github.com/sarahjenkins-dev/code-guard-ai',
      skills: ['TypeScript', 'Python', 'GitHub Actions', 'AST Parsing'],
      status: 'Published',
    },
  ],
  testimonials: [
    {
      id: 'test-1',
      clientName: 'David K. Vance',
      clientRole: 'VP of Engineering at FinEdge Global',
      feedback:
        'Sarah delivered our AI microservices pipeline two weeks ahead of schedule. Her attention to detail in high-concurrency systems, API design, and prompt evaluation is world-class.',
      date: 'October 2024',
    },
    {
      id: 'test-2',
      clientName: 'Elena Rostova',
      clientRole: 'Co-founder & CTO at Synthetix Labs',
      feedback:
        'Phenomenal engineer. She translated ambiguous product requirements into a rock-solid, production-grade RAG pipeline that now powers our core SaaS product.',
      date: 'July 2024',
    },
  ],
  experiences: [
    {
      id: 'exp-1',
      company: 'Nexus Systems',
      role: 'Lead AI & Backend Systems Engineer',
      location: 'San Francisco, CA',
      dates: 'Oct 2022 – Present',
      bullets: [
        'Spearheaded user onboarding AI intelligence across 4 core product surfaces, boosting 30-day user retention by 24% and reducing latency by 35%.',
        'Architected comprehensive microservices ecosystem with FastAPI, Celery, and Redis handling 8M+ daily requests with 99.98% uptime.',
        'Orchestrated end-to-end LLM orchestration workflows for 14 cross-functional engineers, accelerating delivery cycles by 3 weeks.',
      ],
    },
    {
      id: 'exp-2',
      company: 'Apex Financial Technologies',
      role: 'Senior Machine Learning Engineer',
      location: 'San Francisco, CA',
      dates: 'Jan 2020 – Sep 2022',
      bullets: [
        'Directed end-to-end ML model lifecycle for high-volume analytics platform processing $2.4B in annual transaction flows.',
        'Conducted 40+ iterative model benchmarking sessions, achieving 94% accuracy on complex anomaly detection flows.',
        'Championed performance optimization, uplifted API throughput by 3.2x through async batching and TensorRT compilation.',
      ],
    },
    {
      id: 'exp-3',
      company: 'Venture Labs Studio',
      role: 'Software & Data Systems Engineer',
      location: 'San Jose, CA',
      dates: 'Jun 2017 – Dec 2019',
      bullets: [
        'Developed customer-facing backend APIs and ETL pipelines for 6 early-stage SaaS client launches, generating $4.2M in seed capital.',
        'Engineered automated database migrations and CI/CD pipelines that reduced deployment incidents by 65%.',
      ],
    },
  ],
  education: [
    {
      id: 'edu-1',
      school: 'University of California, Berkeley',
      degree: 'Bachelor of Science (B.S.) in Computer Science & Cognitive Systems',
      dates: '2013 – 2017',
      fieldOfStudy: 'Computer Science & AI Systems',
      description: 'Graduated Magna Cum Laude. Dean’s Honors List (2014–2017). Lead researcher at Berkeley AI Research Lab.',
    },
    {
      id: 'edu-2',
      school: 'Stanford University (Online)',
      degree: 'Graduate Certificate in Deep Learning & Distributed Systems',
      dates: '2019',
      fieldOfStudy: 'Distributed Systems & Scalable ML',
      description: 'Specialization in low-latency inferencing, model quantization, and distributed cloud computing.',
    },
  ],
};

export const PARTNER_LOGOS = [
  {
    name: 'Nexus Core',
    url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBy5-OfCwGwuBBNGaA7TYC0xSvh0W1kLq0m31yb-KjgjteKYO1Wt4bsMpCFRknh6vrfFsCaKp7qtRgsR8Sbcqo03E4luDSbO3SImgVQlazSxc2UXahXqwX-O0cNMKqimIFWfAiuQsFoZj7vZguQYlUTuN-Lni4ZO4B3jw220U-sq1vWvLhtYd3afKvzbKB6P1xXSVJVLYTTEleyAoLBH-RN63vw3aY5DyAfsqklRc8v5oTLW_PvtnUvtg',
  },
  {
    name: 'Apex Financial',
    url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAN00lDJsErwCCnFY6pVSuY__gGI05tXNvJ9d8FimnzBVUoHbwEhf4srALxO6PFx1CFfzVT2LxVrew7yaKkSrWp6Hd1Dd3YLaQss-4JGl-q64hIIC-8gBQEHj0ZHB6BMRQfWjeQL3ob9l6Jp87UqK5Q2ZuT3AWTFxnhOJEiBfl3vtgkZlmIJYnmCLzfJeI91NTJVJlbs0pwRiaEF-3nowyCp6Mk-uF7FSLrhCvzSuB-rqKOAiHAO6kPfw',
  },
  {
    name: 'Venture Labs',
    url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDEQDf2dU3D7l4rKLDExgIvlYvjMgawwDkAK48zQhoBjKWQfcwtf4q6us2J8f3OZDoUwWtIzjoLcdcc8ThPKBXcyTjz34GyatwGRF6VsB3RGeU1oiRfCTPXWQ7Tk-J3UGg7jWS_6hfMXZadwiU53rfhE2gcdEQPMvMexzSCSuudI12TpyYWfY9-f8CQDhetG0kgdVV5PvJhIDZ51-B3t_AEj_2VK64B1G6Yg9ltPERo-QBU4jAjdnOb2Q',
  },
  {
    name: 'Global Consulting',
    url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuABWn6hGK47FmYDZcTPR835wWR8jIJxLXsZE9rjJocMtvFq7b2QolQgUI8MQZY-eRau6ym2wGRmS81OwAoq3E-h8lQp1ho1JcQIjuwS7Ply-E-eTOxxgFHzeCCITde3KX1uETeHhWtFUH2WscAB1mLICQxalq5ZFG_SfA8hvRZ278_FaUJ1VaYwZdHpAzjVibpE7124GZDrbmYqHf03zD1cOXJ1RGZfz2Mum2igm_17ECk232Uclm4aUQ',
  },
];

export const INITIAL_ATS_DATA: AtsBreakdown = {
  overallScore: 85,
  scoreStatus: 'Excellent',
  summary: 'Your resume strongly aligns with the job description. Resolving the targeted suggestions below will push your ATS pass probability to 96%.',
  keywordsScore: 92,
  keywordsSummary: 'Strong presence of primary skills (Figma, UX Research). Missing high-value phrases: "WCAG 2.1 Accessibility" and "Interactive Prototyping".',
  formattingScore: 88,
  formattingSummary: 'Clean single-column hierarchy. Minor inconsistent date formatting detected across 2 previous roles.',
  impactScore: 65,
  impactSummary: 'Key achievements lack quantitative business metrics (conversion %, revenue, time-to-market).',
  targetRole: 'Senior Product Designer (Acme Corp)',
  suggestions: [
    {
      id: 'sug-1',
      type: 'warning',
      title: 'Unquantified Achievement in Lead Role',
      category: 'impact',
      problem: 'Vague phrasing in experience bullet: "Spearheaded user onboarding redesign, improving user retention and team workflows."',
      suggestedFix: 'Quantified outcome: "Spearheaded user onboarding redesign across 4 core product surfaces, boosting 30-day user retention by 24% and reducing drop-off by 18% over 6 months."',
      impactBoost: '+15% Impact Score',
      applied: false,
    },
    {
      id: 'sug-2',
      type: 'lightbulb',
      title: "Missing High-Priority Keyword: 'Interactive Prototyping'",
      category: 'keyword',
      problem: 'The target job description emphasizes "Interactive Prototyping" and "Component Design Systems" 4 times. These exact keyword matches are currently missing from your professional summary.',
      suggestedFix: 'Add tailored phrase to Summary: "Specializing in interactive prototyping, design tokens, and building scalable WCAG 2.1 compliant enterprise design systems."',
      impactBoost: '+6% Keywords Score',
      applied: false,
    },
    {
      id: 'sug-3',
      type: 'warning',
      title: 'Passive Verb Usage in Collaboration Bullet',
      category: 'impact',
      problem: 'Passive phrasing detected: "Responsible for managing design handoffs and coordinating feedback with frontend developers."',
      suggestedFix: 'Active action-verb framing: "Orchestrated end-to-end design handoff workflows for 14 cross-functional engineers, accelerating delivery cycles by 3 weeks."',
      impactBoost: '+8% Impact Score',
      applied: false,
    },
    {
      id: 'sug-4',
      type: 'lightbulb',
      title: 'Inconsistent Date Format Across Work History',
      category: 'format',
      problem: 'Inconsistent date formatting detected: Mixed "10/2022 - Present" and "Jan 2020 - Sept 2022", which can trigger parsing errors in legacy ATS software.',
      suggestedFix: 'Standardize to standard ATS format: "Oct 2022 – Present" and "Jan 2020 – Sep 2022".',
      impactBoost: '+4% Formatting Score',
      applied: false,
    },
  ],
};

export const INITIAL_TAILORED_CV: TailoredCvData = {
  name: 'Sarah Jenkins',
  role: 'Senior Product Designer',
  email: 'sarah.jenkins@example.com',
  phone: '+1 (555) 019-2834',
  location: 'San Francisco, CA',
  linkedin: 'linkedin.com/in/sarahjenkins-design',
  summary:
    'Award-winning Senior Product Designer with 8+ years of expertise in crafting scalable enterprise SaaS interfaces, high-fidelity interactive prototyping, and architecting WCAG 2.1 AA accessible design systems. Proven track record of boosting 30-day user retention by 24% and driving conversion velocity across multi-platform cloud ecosystems.',
  skills: [
    'Figma',
    'Interactive Prototyping',
    'Design Systems',
    'WCAG 2.1 Accessibility',
    'User Research & Testing',
    'Data Visualization',
    'Information Architecture',
    'Design Tokens',
    'Agile Sprints',
    'Cross-Functional Leadership',
  ],
  experiences: [
    {
      id: 'exp-1',
      company: 'Nexus Systems',
      role: 'Lead UX / Product Designer',
      location: 'San Francisco, CA',
      dates: 'Oct 2022 – Present',
      bullets: [
        'Spearheaded user onboarding redesign across 4 core product surfaces, boosting 30-day user retention by 24% and cutting drop-off by 18% over 6 months.',
        'Architected comprehensive multi-brand design system with 180+ reusable component tokens in Figma, cutting engineering handoff velocity by 35%.',
        'Orchestrated end-to-end design handoff workflows for 14 cross-functional engineers, accelerating delivery cycles by 3 weeks.',
      ],
    },
    {
      id: 'exp-2',
      company: 'Apex Financial Technologies',
      role: 'Senior UX Designer',
      location: 'San Francisco, CA',
      dates: 'Jan 2020 – Sep 2022',
      bullets: [
        'Directed end-to-end product design for high-volume analytics dashboard processing $2.4B in annual transaction flows.',
        'Conducted 40+ moderated usability test sessions, achieving 94% task completion rate on complex portfolio rebalancing flows.',
        'Championed accessibility audit, uplifting 12 product modules to full WCAG 2.1 AA compliance.',
      ],
    },
    {
      id: 'exp-3',
      company: 'Venture Labs Studio',
      role: 'Product Designer',
      location: 'San Jose, CA',
      dates: 'Jun 2017 – Dec 2019',
      bullets: [
        'Designed customer-facing web and mobile applications for 6 early-stage SaaS client launches, generating $4.2M in seed capital.',
        'Built interactive micro-interaction prototypes that boosted user satisfaction CSAT scores from 3.8 to 4.7 out of 5.',
      ],
    },
  ],
  education: [
    {
      id: 'edu-1',
      school: 'University of California, Berkeley',
      degree: 'B.S. in Cognitive Science & Human-Computer Interaction',
      dates: '2013 – 2017',
    },
    {
      id: 'edu-2',
      school: 'Nielsen Norman Group',
      degree: 'Master UX Certified Practitioner (UXMC)',
      dates: '2019',
    },
  ],
};

export const INITIAL_COVER_LETTER: CoverLetterData = {
  applicantName: 'Alex Mercer',
  applicantTitle: 'Senior Product Designer',
  email: 'alex.mercer@email.com',
  phone: '(555) 123-4567',
  location: 'San Francisco, CA',
  linkedin: 'linkedin.com/in/alexmercer',
  date: 'October 24, 2024',
  hiringManager: 'Hiring Manager',
  companyName: 'Acme Corp',
  companyAddress: '123 Innovation Drive',
  cityStateZip: 'Tech City, TC 94016',
  paragraphs: [
    'I am writing to express my strong interest in the Senior Product Designer position at Acme Corp. With over eight years of experience designing scalable enterprise SaaS platforms and a proven track record of reducing user onboarding time by up to 40%, I am excited about the opportunity to bring my strategic design thinking to your innovative product team.',
    'In my current role at Nexus Systems, I led the comprehensive redesign of our core analytics dashboard. By implementing a rigorous design system and conducting extensive user research, our team successfully increased daily active usage by 25%. I noticed that Acme Corp is currently expanding its data visualization tools, and I believe my background in translating complex data into intuitive, actionable interfaces aligns perfectly with your roadmap.',
    'What draws me specifically to Acme Corp is your commitment to accessibility and inclusive design. Throughout my career, I have championed WCAG compliance, ensuring that digital products are usable by everyone. I am eager to contribute to a culture that values empathy and rigorous user testing as much as aesthetic excellence.',
    "I would welcome the opportunity to discuss how my experience in cross-functional collaboration and my passion for crafting elegant solutions can contribute to Acme Corp's continued success. Thank you for your time and consideration.",
  ],
  signatureName: 'Alex Mercer',
};

export const INITIAL_APPLICATIONS: JobApplication[] = [
  {
    id: 'app-1',
    company: 'Acme Corp',
    role: 'Senior Product Designer',
    logoText: 'AC',
    status: 'Interviewing',
    appliedDate: 'Oct 24, 2024',
    atsScore: 90,
    location: 'San Francisco, CA (Hybrid)',
    salary: '$165k - $190k',
    notes: 'Technical panel interview scheduled with VP of Design next Tuesday.',
  },
  {
    id: 'app-2',
    company: 'TechFlow',
    role: 'Senior UX Architect',
    logoText: 'TF',
    status: 'Applied',
    appliedDate: 'Oct 21, 2024',
    atsScore: 85,
    location: 'Remote',
    salary: '$150k - $175k',
    notes: 'Submitted tailored resume and custom cover letter highlighting design systems.',
  },
  {
    id: 'app-3',
    company: 'Nexus Systems',
    role: 'Staff Product Designer',
    logoText: 'NS',
    status: 'Offer',
    appliedDate: 'Oct 15, 2024',
    atsScore: 94,
    location: 'New York, NY (Remote)',
    salary: '$185k - $210k',
    notes: 'Offer letter received. Reviewing equity package.',
  },
  {
    id: 'app-4',
    company: 'Stripe Horizon',
    role: 'Principal UX Researcher',
    logoText: 'SH',
    status: 'Draft',
    appliedDate: 'Oct 26, 2024',
    atsScore: 82,
    location: 'Seattle, WA',
    salary: '$170k - $200k',
    notes: 'Tailoring CV for payments and financial UX metrics.',
  },
];
